--DROP TABLE TRMS_PASSWORDS;
--DROP TABLE TRMS_EVENTS;
--DROP TABLE TRMS_ATTACHMENTS;
--DROP TABLE TRMS_APPLICATIONS;
--DROP TABLE TRMS_EMPLOYEES;

CREATE TABLE TRMS_EMPLOYEES (E_ID NUMBER(10), USERNAME VARCHAR(20), DEPARTMENT VARCHAR(20), DS_ID NUMBER(10), DH_ID NUMBER(10));
                        
CREATE TABLE TRMS_PASSWORDS (E_ID NUMBER(10), PW VARCHAR(30));

CREATE TABLE TRMS_ATTACHMENTS (APP_ID NUMBER(10), DOC_NAME VARCHAR(30), DESCRIPTION VARCHAR(200));

CREATE TABLE TRMS_APPLICATIONS (APP_ID NUMBER(10), E_ID NUMBER(10), BC_ID NUMBER(10),  DEPARTMENT VARCHAR(20), DS_APPROVAL NUMBER(1), 
                                DH_APPROVAL NUMBER(1), BENCO_APPROVAL NUMBER(1), EVENT_ID NUMBER(10), RESPONSE_REQ_ID NUMBER(10), INFO_REQ VARCHAR(200),
                                STATUS VARCHAR(10));
                                
CREATE TABLE TRMS_EVENTS (EVENT_ID NUMBER(10), EVT_DATETIME DATE, EVT_LOCATION VARCHAR(40), EVT_DESCRIPTION VARCHAR(200), 
                            EVT_COST NUMBER(10), GRADING_FORMAT VARCHAR(20), PASSING_GRADE VARCHAR(20), EVENT_TYPE VARCHAR(30), JUSTIFICATION VARCHAR(200));

ALTER TABLE TRMS_EMPLOYEES ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (E_ID);
ALTER TABLE TRMS_APPLICATIONS ADD CONSTRAINT APPLICATIONS_PK PRIMARY KEY (APP_ID);
ALTER TABLE TRMS_EVENTS ADD CONSTRAINT EVENTS_PK PRIMARY KEY (EVENT_ID);

ALTER TABLE TRMS_ATTACHMENTS ADD CONSTRAINT ATTACHMENTS_FK FOREIGN KEY (APP_ID) REFERENCES TRMS_APPLICATIONS(APP_ID);
ALTER TABLE TRMS_PASSWORDS ADD CONSTRAINT PASSWORDS_FK FOREIGN KEY (E_ID) REFERENCES TRMS_EMPLOYEES(E_ID);
ALTER TABLE TRMS_APPLICATIONS ADD CONSTRAINT APPLICATIONS_FK FOREIGN KEY (EVENT_ID) REFERENCES TRMS_EVENTS(EVENT_ID);
ALTER TABLE TRMS_APPLICATIONS ADD CONSTRAINT APPLICATIONS_FK2 FOREIGN KEY (E_ID) REFERENCES TRMS_EMPLOYEES(E_ID); 



